### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by eduswd** [Kitami/BandScoreSplit#5]
I hope I can export higher definition pictures.
thankyou
（I am not good at English，sorry）

**Comment by hibikiwtnb** [comment]
output image's resolution is the same as on input image resolution (will only change high resolution in some not fit aspect ratio) 
because i think that output an image with a higher resolution than the input image does not improve the image quality.

**Comment by eduswd** [comment]
![output image](https://user-images.githubusercontent.com/62463186/77280335-f9ffb800-6cfe-11ea-9cc0-780eaec85b23.png)
![input image](https://user-images.githubusercontent.com/62463186/77280346-fc621200-6cfe-11ea-863c-6c95cfd20e88.png)

**Comment by eduswd** [comment]
the first picture is input image,the second picture is output image

**Comment by hibikiwtnb** [comment]
~~did you try to download the image -> right click the image file -> Properties~~
~~and compare to original resolution ?~~
~~when you download the image, it will be download at the original resolution.~~

OK,i found the cause of the problem, it will be fix soon. 
It Probably because it used floating-point value in trimming the image function, and it should be int value.

**Comment by eduswd** [comment]
OK，thankyou
